version: '3'

services:
    docker-mysql:
        image: mysql:latest
    


    environment:
        - MYSQL_ROOT_PASSWORD=12345
        - MYSQL_DATABASE=restful-api
        - MYSQL_PASSWORD=

phpmyadmin:
image: phpmyadmin/phpmyadmin
links:
- docker-mysql
environment:
    PMA_HOST: docker-mysql
    PMA_PORT: 3306
ports:
    - '8181:81'
docker-webapp:
image: demojpa/demojpa-0.0.1-SNAPSHOT
depends_on:
    - docker-mysql
ports:
- 8082:8081
    environment:
        - DATABASE_HOST=docker-mysql
        - DATABASE_USER=root
        - DATABASE_PASSWORD=
        - DATABASE_NAME=restful-api
        - DATABASE_PORT=3306